__title__ = "syzqemuctl"
__version__ = "0.3.3"
__description__ = "A command-line tool for managing QEMU disk images and virtual machines created through Syzkaller's create-image.sh."
__author__ = "Zhiyu Zhang"
__email__ = "zhiyuzhang999@gmail.com"
__license__ = "Apache-2.0"
__url__ = "https://github.com/QGrain/syzqemuctl"